version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
    command: >
      bash -c 
      "
      cd back-end/app/ 
      &&
      python manage.py migrate
      && 
      python manage.py loaddata db.json
      && 
      python manage.py runserver 0.0.0.0:8080
      "
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      POSTGRES_USER: dies_admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.3
    env_file:
      - .env
    environment:
      POSTGRES_USER: dies_admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
volumes:
  postgres_data:

