# Generated by Django 4.0.6 on 2023-08-31 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=30, null=True, verbose_name='имя пользователя')),
                ('bio', models.TextField(blank=True, max_length=300, null=True, verbose_name='биография')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='баланс')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=userapp.models.load_to_avatar)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
