# Generated by Django 4.0.6 on 2023-08-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='наименование категории')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.categoriesimage')),
                ('subcategories', models.ManyToManyField(null=True, to='shopapp.subcategories')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
